name: build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    tag:
      required: false
      default: 'Hello'
      type: string

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/upload-artifact@v2
        with:
          name: source
          path: |
            ./*
            !.git/config

  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Vite Build
        run: pnpm build

      - uses: ncipollo/release-action@v1
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
        with:
          artifacts: "release/*.deb"
          allowUpdates: true

      - uses: ncipollo/release-action@v1
        if: ${{ success() && matrix.os == 'windows-latest' }}
        with:
          artifacts: "release/*.exe"
          allowUpdates: true

      - uses: ncipollo/release-action@v1
        if: ${{ success() && matrix.os == 'macos-latest' }}
        artifacts: "release/*.dmg"
        allowUpdates: true